import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {Header} from "../components/header";
import {LimitedStonksBody} from "@/components/limited-stonks-body";
import {Footer} from "@/components/footer";
import {VipStonksBody} from "@/components/vip-stonks-body";
import {AutomaticBody} from "@/components/automatic-body";
import {BookBody} from "@/components/book-body";

const inter = Inter({ subsets: ['latin'] })

export default function Book() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Header/>
                <BookBody/>
                <Footer/>
            </main>
        </>
    )
}
