import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import {Telegram} from "@/components/telegram";
import Script from "next/script";
import * as fbq from '../lib/fpixel'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
        <Script
            id="fb-pixel"
            strategy="afterInteractive"
            dangerouslySetInnerHTML={{
                __html: `
            !function(f,b,e,v,n,t,s)
            {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
            n.callMethod.apply(n,arguments):n.queue.push(arguments)};
            if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
            n.queue=[];t=b.createElement(e);t.async=!0;
            t.src=v;s=b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t,s)}(window, document,'script',
            'https://connect.facebook.net/en_US/fbevents.js');
            fbq('init', 621225559735238);
          `,
            }}
        />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          {/*<p>fgag</p>*/}
        {/*<Header/>*/}
          <Telegram/>
          {/*<Footer/>*/}
      </main>
    </>
  )
}
